#!/usr/bin/env python3
"""Single source of truth for the talk: script.json -> docs/SPEAKER-SCRIPT.md and the <aside> notes in index.html.
Run from anywhere: python3 showcase/deck/build.py   (fails if the script and the deck's slides drift apart)"""
import json, re, html, os, sys
D = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(D, "..", ".."))
S = json.load(open(os.path.join(D, "script.json"), encoding="utf-8"))
slides = S["slides"]

def mmss(sec): return f"{sec//60}:{sec%60:02d}"
full = sum(s["seconds"] for s in slides)
trimmed = full - sum(s["seconds"] for s in slides if s.get("skip")) - sum(s.get("trim", 0) for s in slides if not s.get("skip"))

# ---- patch index.html notes (drift guard first) ----
idx_path = os.path.join(D, "index.html"); idx = open(idx_path, encoding="utf-8").read()
titles = re.findall(r'<section class="slide [^"]*" data-title="([^"]*)"', idx)
want = [s["title"] for s in slides]
if titles != want:
    sys.exit(f"DRIFT: deck slides {titles} != script slides {want}")
it = iter(slides)
def repl(_m):
    s = next(it)
    return "<aside hidden>" + html.escape(("Cue: " + s["cue"] + " — " if s.get("cue") else "") + s["say"], quote=False) + "</aside>"
new, n = re.subn(r"<aside hidden>.*?</aside>", repl, idx, flags=re.S)
if n != len(slides): sys.exit(f"DRIFT: {n} asides vs {len(slides)} slides")
open(idx_path, "w", encoding="utf-8").write(new)

# ---- speaker script markdown ----
L = ["# Jadal — speaker script", "",
     "Generated from `showcase/deck/script.json` by `showcase/deck/build.py`. The same text is the per-slide speaker notes in the deck (press **N**). Edit the JSON, then re-run the build; do not edit this file or the deck's notes by hand.", "",
     "Deck: http://127.0.0.1:5190/deck/ · keys: ← → move, N notes, F fullscreen.", "",
     "## Honesty rules for the talk", "", S["meta"]["rules"], "",
     "## Time budget", "",
     f"Full talk: **{mmss(full)}**. Trimmed (skip the slide marked *skip*, shorten the one marked *trim*): **{mmss(trimmed)}**. Times are speaking time at a calm pace.", "",
     "| # | Slide | Time | Running | Note |", "|---|---|---|---|---|"]
run = 0
for i, s in enumerate(slides, 1):
    run += s["seconds"]
    note = "skip when short" if s.get("skip") else (f"trim by {s['trim']} s when short" if s.get("trim") else "")
    L.append(f"| {i} | {s['title']} | {mmss(s['seconds'])} | {mmss(run)} | {note} |")
L += ["", "## Full script, slide by slide", ""]
for i, s in enumerate(slides, 1):
    L += [f"### Slide {i} — {s['title']} ({mmss(s['seconds'])})", "", f"**Stage cue:** {s['cue']}", "", f"> {s['say']}", ""]
L += ["## 30-second version", "", f"> {S['short30']}", "", "## 2-minute version", ""]
for k in S["short2min"]:
    L += [f"**{k['slide']}.** {k['say']}", ""]
L += ["## If asked", ""]
for k in S["ifasked"]:
    L += [f"**{k['q']}**", "", f"> {k['a']}", ""]
out = os.path.join(ROOT, "docs", "SPEAKER-SCRIPT.md")
open(out, "w", encoding="utf-8").write("\n".join(L))
print(f"ok: {len(slides)} slides, full {mmss(full)}, trimmed {mmss(trimmed)} -> {out}")
