/**
 * C7 Demo mode: guided walkthrough actions on top of the shared typed API client.
 *
 * Each step calls the real routes through `src/api` (live backend, or the
 * contract-validated mock when VITE_MOCK is not "0"). Every figure shown comes
 * from those responses; this module only picks rows and reshapes them.
 */

import { api, isMockMode } from "../api";

export interface ApiResult<T> {
  ok: boolean;
  data?: T;
  error?: string;
  /** True when the response comes from the local mock (demo mode). */
  mocked: boolean;
}

export interface DemoEvent {
  id: string;
  at: string;
  type: string;
  canal_id?: string;
  summaryEn: string;
  summaryTe: string;
}

export interface AuditResult {
  conservationOk: boolean;
  giniBefore: number;
  giniAfter: number;
  summaryEn: string;
  summaryTe: string;
}

async function run<T>(fn: () => Promise<T>): Promise<ApiResult<T>> {
  try {
    return { ok: true, data: await fn(), mocked: isMockMode() };
  } catch (err) {
    return { ok: false, error: err instanceof Error ? err.message : String(err), mocked: isMockMode() };
  }
}

async function firstWindowId(index = 0): Promise<string> {
  const windows = await api.releaseWindows();
  const win = windows[index] ?? windows[0];
  if (!win) throw new Error("no release window");
  return win.id;
}

// ---------------------------------------------------------------------------
// Demo controls (contracts: demoReset, demoAdvance, events)
// ---------------------------------------------------------------------------

export function demoReset(): Promise<ApiResult<{ ok: boolean }>> {
  return run(() => api.demoReset());
}

export function demoAdvance(hours: number): Promise<ApiResult<{ now: string }>> {
  return run(() => api.demoAdvance({ hours }));
}

let eventSeq = 0;
/** A timeline marker generated by the walkthrough itself (not a server event). */
export function mockEvent(type: string, en: string, te: string): DemoEvent {
  eventSeq += 1;
  return { id: `demo-${eventSeq}`, at: new Date().toISOString(), type, canal_id: "c1", summaryEn: en, summaryTe: te };
}

/** Server events (GET /api/events) mapped to timeline rows. */
export function fetchEvents(): Promise<ApiResult<DemoEvent[]>> {
  return run(async () => {
    const list = await api.events();
    return list.map((e) => {
      const text = `${e.type} (${e.actor.kind}: ${e.actor.id})`;
      return { id: e.id, at: e.at, type: e.type, canal_id: e.canal_id, summaryEn: text, summaryTe: text };
    });
  });
}

// ---------------------------------------------------------------------------
// Per-step actions.
// ---------------------------------------------------------------------------

export interface CompareResult {
  equalHoursGini: number;
  equalWaterGini: number;
  tailBeforePct: number;
  tailAfterPct: number;
}

export function compareRosters(): Promise<ApiResult<CompareResult>> {
  return run(async () => {
    const windowId = await firstWindowId();
    const [hours, water] = await Promise.all([
      api.proposeRoster({ release_window_id: windowId, mode: "equal_hours" }),
      api.proposeRoster({ release_window_id: windowId, mode: "equal_water" }),
    ]);
    // need_met rows are ordered head to tail; the last row is the tail outlet.
    const tailBefore = hours.need_met[hours.need_met.length - 1];
    const tailAfter = water.need_met[water.need_met.length - 1];
    if (!tailBefore || !tailAfter) throw new Error("no need-met rows");
    return {
      equalHoursGini: hours.comparison.equal_hours_gini,
      equalWaterGini: water.comparison.equal_water_gini,
      tailBeforePct: tailBefore.pct,
      tailAfterPct: tailAfter.pct,
    };
  });
}

export interface UrgentRequestResult {
  requestId: string;
  transcriptTe: string;
  recommendation: string;
  decision: string;
}

export function raiseUrgentRequest(): Promise<ApiResult<UrgentRequestResult>> {
  return run(async () => {
    const intake = await api.intake({ farmer_id: "f1", text: "నాకు అత్యవసరంగా నీరు కావాలి, వరి పూత దశలో ఉంది" });
    const raised =
      intake.request ??
      (await api.raiseRequest({
        farmer_id: "f1",
        type: "urgent",
        volume_m3: 0,
        reason: intake.transcript_te,
        channel: "voice",
      }));
    const rec = raised.agent_recommendation;
    const decided = await api.decideRequest(raised.id, {
      decision: "approve",
      volume_m3: rec?.volume_m3 ?? raised.volume_m3,
    });
    return {
      requestId: decided.id,
      transcriptTe: intake.transcript_te,
      recommendation: rec
        ? `${rec.decision} ${rec.volume_m3} m³: ${rec.rationale}`
        : `intent ${intake.intent}, urgency ${intake.urgency}, asked ${raised.volume_m3} m³`,
      decision: `${decided.status}${decided.coordinator_decision ? ` ${decided.coordinator_decision.volume_m3} m³` : ""}`,
    };
  });
}

export interface NotifyResult {
  callsPlaced: number;
  voiceOnly: string[];
  whatsapp: string[];
}

export function replanAndNotify(): Promise<ApiResult<NotifyResult>> {
  return run(async () => {
    const windowId = await firstWindowId();
    const { roster } = await api.proposeRoster({ release_window_id: windowId, mode: "equal_water" });
    const approved = await api.approveRoster(roster.id);
    const [contacts, farmers] = await Promise.all([api.contacts(), api.listFarmers()]);
    const names = new Map(farmers.map((r) => [r.farmer.id, r.farmer.name]));
    const label = (id: string) => `${id} (${names.get(id) ?? id})`;
    return {
      callsPlaced: approved.contacts_queued,
      voiceOnly: contacts.filter((c) => c.channel === "voice").map((c) => label(c.farmer_id)),
      whatsapp: contacts.filter((c) => c.channel !== "voice").map((c) => label(c.farmer_id)),
    };
  });
}

export interface NightProtocolResult {
  windowId: string;
  startsAtIst: string;
  warningsSent: number;
}

function istClock(iso: string): string {
  const parts = new Intl.DateTimeFormat("en-GB", { timeZone: "Asia/Kolkata", hour: "2-digit", minute: "2-digit", hour12: false }).format(new Date(iso));
  return `${parts} IST`;
}

export function fireNightProtocol(): Promise<ApiResult<NightProtocolResult>> {
  return run(async () => {
    await api.demoAdvance({ hours: 1 });
    const [windows, contacts] = await Promise.all([api.releaseWindows(), api.contacts()]);
    const win = windows[1] ?? windows[0];
    if (!win) throw new Error("no release window");
    return { windowId: win.id, startsAtIst: istClock(win.start), warningsSent: contacts.length };
  });
}

export interface BufferResult {
  /** Buffer volume reported by the ledger. */
  bufferM3: number;
  requester: string;
  /** Volume of the buffer request raised for the requester (from the API's own buffer request). */
  requestedM3: number | null;
}

export function releaseToBuffer(): Promise<ApiResult<BufferResult>> {
  return run(async () => {
    const [ledger, requests, farmers] = await Promise.all([api.ledger(), api.listRequests(), api.listFarmers()]);
    const names = new Map(farmers.map((r) => [r.farmer.id, r.farmer.name]));
    // The walkthrough replays the buffer request that is already on record for the requester.
    const existing = requests.find((r) => r.type === "buffer");
    let requestedM3: number | null = null;
    let requester = "f7";
    if (existing) {
      const raised = await api.raiseRequest({
        farmer_id: existing.farmer_id,
        type: "buffer",
        volume_m3: existing.volume_m3,
        reason: existing.reason,
        channel: existing.channel,
      });
      requestedM3 = raised.volume_m3;
      requester = raised.farmer_id;
    }
    return { bufferM3: ledger.balances.buffer_m3, requester: `${requester} (${names.get(requester) ?? requester})`, requestedM3 };
  });
}

export function fetchAudit(): Promise<ApiResult<AuditResult>> {
  return run(async () => {
    const [audit, windowId] = await Promise.all([api.audit(), firstWindowId()]);
    const water = await api.proposeRoster({ release_window_id: windowId, mode: "equal_water" });
    return {
      conservationOk: audit.balances.conservation_ok,
      giniBefore: water.comparison.equal_hours_gini,
      giniAfter: water.comparison.equal_water_gini,
      summaryEn: audit.summary_en,
      summaryTe: audit.summary_te,
    };
  });
}
