#!/usr/bin/env node
/**
 * Generates `docs/research/crop-params-provenance.md` from the SHIPPED `crop-params.json`.
 *
 * COMPUTED + rerunnable:
 *   pnpm --filter @jadal/core gen:provenance
 *
 * It does no water arithmetic and mutates no value: it reads each row, derives the provenance
 * verdict with the same module the vitest uses (`src/data/crop-params-provenance.ts`), and renders a
 * `crop x field -> value, status, source, finding` table. The output is deterministic, so re-running
 * it in CI should be a no-op diff.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  MAX_SOURCED_PAGE,
  checkAll,
  provenanceRows,
  type CropParamsJsonRow,
} from '../src/data/crop-params-provenance.ts';

const here = dirname(fileURLToPath(import.meta.url));
const jsonPath = resolve(here, '../src/data/crop-params.json');
const outPath = resolve(here, '../../../docs/research/crop-params-provenance.md');

const rows = JSON.parse(readFileSync(jsonPath, 'utf8')) as CropParamsJsonRow[];

/** Makes arbitrary text safe inside a markdown table cell. */
function cell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();
}

function renderValue(value: unknown): string {
  if (value === null) return 'null';
  if (typeof value === 'object') return JSON.stringify(value);
  return String(value);
}

const statusCounts: Record<string, number> = { MEASURED: 0, ASSUMED: 0, UNSOURCED: 0 };
let taggedFields = 0;
const tableLines: string[] = [];

for (const row of rows) {
  const cropLabel = `${row.crop}${row.variant ? ` (${row.variant})` : ''}`;
  for (const field of provenanceRows(row)) {
    taggedFields += 1;
    if (field.status !== undefined && field.status in statusCounts) {
      statusCounts[field.status] = (statusCounts[field.status] ?? 0) + 1;
    }
    const source = field.sourceClause ?? '_(no source clause names this field)_';
    tableLines.push(
      `| ${cell(cropLabel)} | \`${field.field}\` | \`${cell(renderValue(field.value))}\` | ` +
        `${field.status ?? '**MISSING**'} | ${cell(source)} | ${cell(field.finding)} |`,
    );
  }
}

const violations = checkAll(rows);

const doc = `# crop-params provenance

**COMPUTED**, rerunnable. Generated by \`packages/core/scripts/generate-crop-params-provenance.ts\`
from the shipped \`packages/core/src/data/crop-params.json\`. Do not edit this file by hand; run:

\`\`\`bash
pnpm --filter @jadal/core gen:provenance
\`\`\`

This document does not change any numeric value. It records, per field, whether the value is
**MEASURED** against FAO-56 Rev.1 (2025), **ASSUMED** (a project/regional value), or **UNSOURCED**
(the row has no valid citation at all).

## Summary

| Metric | Value |
| :--- | ---: |
| Crop rows | ${rows.length} |
| Tagged agronomic fields | ${taggedFields} |
| MEASURED fields | ${statusCounts.MEASURED ?? 0} |
| ASSUMED fields | ${statusCounts.ASSUMED ?? 0} |
| UNSOURCED fields | ${statusCounts.UNSOURCED ?? 0} |
| Provenance violations | ${violations.length} |
| Page ceiling for a MEASURED citation | ${MAX_SOURCED_PAGE} |

A violation means a field lacks a \`constant_status\` tag, carries an unknown one, or is tagged
MEASURED while citing no printed page or a page outside \`1..${MAX_SOURCED_PAGE}\`. The page ceiling is
the last printed page of the unabridged FAO-56 Rev.1 (2025) text, per
[\`docs/research/model-audit.md\`](./model-audit.md) §8.2.

${
  violations.length === 0
    ? '**Result: 0 violations.**'
    : `**Result: ${violations.length} violation(s):**\n\n${violations.map((v) => `- ${v}`).join('\n')}`
}

## crop x field provenance

| Crop | Field | Value | Status | Source (verbatim clause) | Finding |
| :--- | :--- | :--- | :--- | :--- | :--- |
${tableLines.join('\n')}

## Known unsourced rows

- **redgram** — the entire row is **UNSOURCED**. Its earlier citation, \`p. 410\`, points past the end
  of a document whose last printed page is ${MAX_SOURCED_PAGE} (Selected Bibliography), and FAO-56
  Rev.1 (2025) contains no pigeonpea/redgram row. The numeric values are retained unchanged as an
  ASSUMED regional/project proxy. See \`docs/research/model-audit.md\` F-15.
- **rice \`depletion_p\`** — FAO-56 Table 8.2 gives rice only a saturation-basis threshold, not a
  numeric \`p\`; the \`0.20\` here is a project value.
- **paddy \`percolation_mm_day\`** — FAO-56 tabulates no paddy percolation rate.
- **all \`stage_days\`** — the 2025 edition abolished static calendar stage lengths in favour of GDD.
`;

writeFileSync(outPath, doc, 'utf8');
console.log(
  `wrote ${outPath}\n  rows=${rows.length} fields=${taggedFields} ` +
    `MEASURED=${statusCounts.MEASURED ?? 0} ASSUMED=${statusCounts.ASSUMED ?? 0} ` +
    `UNSOURCED=${statusCounts.UNSOURCED ?? 0} violations=${violations.length}`,
);
